name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    if: github.repository_owner == 'viamrobotics'
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/cirruslabs/flutter:latest

    name: "Publish to pub.dev"
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Publish - dry run
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: flutter pub publish -f
