name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    if: github.repository_owner == 'viamrobotics'
    runs-on: buildjet-2vcpu-ubuntu-2204
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: flutter pub publish --force
